create table cushion (
  uuid       varchar(16),
  ts         timestamp,
  ch0        int,
  ch1        int,
  ch2        int,
  ch3        int,
  ch4        int,
  ch5        int,
  ch6        int,
  ch7        int,
  ch8        int,
  ch9        int,
  ch10       int,
  ch11       int,
  ch12       int,
  ch13       int,
  ch14       int,
  ch15       int,
  ch16       int,
  ch17       int,
  ch18       int,
  ch19       int,
  ch20       int,
  ch21       int,
  ch22       int,
  ch23       int,
  ch24       int,
  ch25       int,
  ch26       int,
  ch27       int,
  ch28       int,
  ch29       int,
  ch30       int,

  max        int,
  sum        int,
  mean       int,
  detect     int,
  stddev     int,
  front      int,
  middle     int,
  rear       int,
  left_      int,
  center     int,
  right_     int,
  minx1      int,
  maxX1      int,
  cntx1      int,
  miny1      int,
  maxy1      int,
  cnty1      int,
  minx2      int,
  maxx2      int,
  cntx2      int,
  miny2      int,
  maxy2      int,
  cnty2      int,
  minx3      int,
  maxX3      int,
  cntx3      int,
  miny3      int,
  maxy3      int,
  cnty3      int,

  diff       int,
  primary key (uuid, ts)
);

create table events (
  uuid       varchar(16),
  ts         timestamp,
  code       smallint,
  message    varchar(128)
);
