create table cushion (
  uuid       varchar(16),
  ts         timestamp,
  ch0        smallint,
  ch1        smallint,
  ch2        smallint,
  ch3        smallint,
  ch4        smallint,
  ch5        smallint,
  ch6        smallint,
  ch7        smallint,
  ch8        smallint,
  ch9        smallint,
  ch10       smallint,
  ch11       smallint,
  ch12       smallint,
  ch13       smallint,
  ch14       smallint,
  ch15       smallint,
  ch16       smallint,
  ch17       smallint,
  ch18       smallint,
  ch19       smallint,
  ch20       smallint,
  ch21       smallint,
  ch22       smallint,
  ch23       smallint,
  ch24       smallint,
  ch25       smallint,
  ch26       smallint,
  ch27       smallint,
  ch28       smallint,
  ch29       smallint,
  ch30       smallint,
  _max       smallint,
  _sum       smallint,
  _avg       smallint,
  _detect    smallint,
  _stddev    smallint,
  constraint ckey primary key (
    uuid
  )
);
